import { jsPDF } from 'jspdf';
import { Attempt, Question, Bookmark } from '../types';
import { UserProfile } from './userProfile';
import { generateComprehensiveReport, ComprehensiveReportData } from './comprehensiveReportEngine';

export async function downloadComprehensiveDiagnosticPdf(
  profile: UserProfile,
  attempts: Attempt[],
  bookmarks: Bookmark[] = [],
  missedQuestions: Question[] = [],
  onProgress?: (status: string) => void
): Promise<boolean> {
  try {
    if (onProgress) onProgress('Compiling diagnostic assessment data...');
    const data: ComprehensiveReportData = generateComprehensiveReport(profile, attempts, bookmarks, missedQuestions);

    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 14;
    const contentWidth = pageWidth - margin * 2;

    // Colors
    const primaryColor = [30, 58, 138]; // Deep Blue
    const secondaryColor = [79, 70, 229]; // Indigo
    const darkSlate = [15, 23, 42]; // Slate 900
    const lightSlate = [100, 116, 139]; // Slate 500
    const lightBg = [248, 250, 252]; // Slate 50

    // Helper: Header on every page
    const drawPageHeader = (pageNum: number, title: string) => {
      // Top colored bar
      doc.setFillColor(30, 58, 138);
      doc.rect(0, 0, pageWidth, 8, 'F');
      doc.setFillColor(99, 102, 241);
      doc.rect(0, 8, pageWidth, 1.5, 'F');

      // Header Text
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(30, 58, 138);
      doc.text('DSSSB TGT / PGT COMPUTER SCIENCE • CANDIDATE PERFORMANCE DOSSIER', margin, 15);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      doc.text(`Candidate: ${data.candidateName} | ID: ${data.profileId} | Date: ${data.generatedDate}`, margin, 19);

      // Section title
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(15, 23, 42);
      doc.text(title, margin, 27);

      // Header line
      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.4);
      doc.line(margin, 29, pageWidth - margin, 29);

      // Footer
      doc.setDrawColor(226, 232, 240);
      doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(7.5);
      doc.setTextColor(148, 163, 184);
      doc.text('Confidential CBT Performance Dossier • Generated by DSSSB PYQ Online (https://dsssbpyq.online)', margin, pageHeight - 7);
      doc.text(`Page ${pageNum} of 4`, pageWidth - margin - 15, pageHeight - 7);
    };

    // ==========================================
    // PAGE 1: Executive Diagnostic Summary & CBT Scorecard
    // ==========================================
    if (onProgress) onProgress('Rendering Page 1: CBT Scorecard & Projected Marks...');
    drawPageHeader(1, 'PAGE 1: EXECUTIVE DIAGNOSTIC SUMMARY & CBT SCORECARD');

    // Candidate ID card box
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(margin, 32, contentWidth, 22, 2, 2, 'F');
    doc.setDrawColor(203, 213, 225);
    doc.roundedRect(margin, 32, contentWidth, 22, 2, 2, 'D');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text(`Candidate Name: ${data.candidateName}`, margin + 5, 38);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(71, 85, 105);
    doc.text(`Target Examination: ${data.targetExam}`, margin + 5, 44);
    doc.text(`Profile Key: ${data.profileId}  |  Assessment Timestamp: ${data.generatedDate}`, margin + 5, 49);

    // Projected Score Highlight Box
    doc.setFillColor(30, 58, 138);
    doc.roundedRect(margin, 58, contentWidth, 34, 3, 3, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(224, 231, 255);
    doc.text('PROJECTED CBT EXAMINATION SCORE (OUT OF 200 MARKS)', margin + 6, 65);

    doc.setFontSize(22);
    doc.setTextColor(255, 255, 255);
    doc.text(`${data.projectedCbtScore.toFixed(1)} / 200`, margin + 6, 76);

    doc.setFontSize(9);
    doc.setTextColor(253, 224, 71); // Amber
    doc.text(`Confidence Range: ${data.scoreConfidenceRange} Marks`, margin + 6, 84);

    // Right side badge in score box
    doc.setFillColor(79, 70, 229);
    doc.roundedRect(pageWidth - margin - 52, 63, 46, 24, 2, 2, 'F');
    doc.setFontSize(7.5);
    doc.setTextColor(224, 231, 255);
    doc.text('READINESS INDEX', pageWidth - margin - 47, 69);
    doc.setFontSize(14);
    doc.setTextColor(255, 255, 255);
    doc.text(`${data.readinessPercentage}%`, pageWidth - margin - 47, 78);
    doc.setFontSize(7);
    doc.setTextColor(199, 210, 254);
    doc.text('DSSSB Cutoff Calibrated', pageWidth - margin - 47, 83);

    // Key Performance Metrics Grid
    const metricBoxWidth = (contentWidth - 6) / 3;
    const metricY = 96;

    // Box 1: Part A
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(margin, metricY, metricBoxWidth, 24, 2, 2, 'F');
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(margin, metricY, metricBoxWidth, 24, 2, 2, 'D');
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 116, 139);
    doc.text('PART A (GENERAL ABILITY)', margin + 4, metricY + 6);
    doc.setFontSize(13);
    doc.setTextColor(15, 23, 42);
    doc.text(`${data.partAScoreEst.toFixed(1)} / 100`, margin + 4, metricY + 14);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    doc.text('Min Qualifying Cutoff: 40 Marks', margin + 4, metricY + 20);

    // Box 2: Part B
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(margin + metricBoxWidth + 3, metricY, metricBoxWidth, 24, 2, 2, 'F');
    doc.roundedRect(margin + metricBoxWidth + 3, metricY, metricBoxWidth, 24, 2, 2, 'D');
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 116, 139);
    doc.text('PART B (CS & PEDAGOGY)', margin + metricBoxWidth + 7, metricY + 6);
    doc.setFontSize(13);
    doc.setTextColor(15, 23, 42);
    doc.text(`${data.partBScoreEst.toFixed(1)} / 100`, margin + metricBoxWidth + 7, metricY + 14);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    doc.text('Min Qualifying Cutoff: 40 Marks', margin + metricBoxWidth + 7, metricY + 20);

    // Box 3: Accuracy & Negative Penalty
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(margin + (metricBoxWidth + 3) * 2, metricY, metricBoxWidth, 24, 2, 2, 'F');
    doc.roundedRect(margin + (metricBoxWidth + 3) * 2, metricY, metricBoxWidth, 24, 2, 2, 'D');
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 116, 139);
    doc.text('ACCURACY & PENALTY', margin + (metricBoxWidth + 3) * 2 + 4, metricY + 6);
    doc.setFontSize(13);
    doc.setTextColor(220, 38, 38);
    doc.text(`${data.overallAccuracy}%`, margin + (metricBoxWidth + 3) * 2 + 4, metricY + 14);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(220, 38, 38);
    doc.text(`Penalty Loss: -${data.totalNegativeMarks} Marks`, margin + (metricBoxWidth + 3) * 2 + 4, metricY + 20);

    // Practice History Summary Table
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text('PRACTICE SESSIONS STATISTICAL SUMMARY', margin, 128);

    const summaryData = [
      ['Total Mocks & Subject Quizzes Attempted', String(data.totalMocksTaken)],
      ['Total Questions Attempted', String(data.totalQuestionsSolved)],
      ['Total Correct Responses (+1.00 each)', `${data.totalCorrect} (+${data.totalCorrect.toFixed(2)} Marks)`],
      ['Total Incorrect Responses (-0.25 penalty)', `${data.totalIncorrect} (-${data.totalNegativeMarks} Marks)`],
      ['Net Aggregate Score Achieved', `${data.totalNetScore.toFixed(2)} Marks`],
      ['Net Accuracy Rate', `${data.overallAccuracy}%`],
    ];

    let tableY = 133;
    summaryData.forEach(([label, value], i) => {
      if (i % 2 === 0) {
        doc.setFillColor(248, 250, 252);
        doc.rect(margin, tableY, contentWidth, 7, 'F');
      }
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(71, 85, 105);
      doc.text(label, margin + 4, tableY + 5);

      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text(value, pageWidth - margin - 4 - doc.getTextWidth(value), tableY + 5);
      tableY += 7.5;
    });

    // Examiner Strategic Takeaway Note Box
    doc.setFillColor(238, 242, 255); // Indigo 50
    doc.roundedRect(margin, 185, contentWidth, 34, 2, 2, 'F');
    doc.setDrawColor(199, 210, 254);
    doc.roundedRect(margin, 185, contentWidth, 34, 2, 2, 'D');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(67, 56, 202);
    doc.text('EXAMINER STRATEGIC TAKEAWAY & QUALIFYING ADVISORY', margin + 4, 192);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(51, 65, 85);
    const takeawayText = [
      '1. DSSSB applies strict mandatory sectional qualifying cutoff: You must secure at least 40% (40/100 for UR)',
      '   in BOTH Part A and Part B independently. Scoring high in one part will not compensate for failing the other.',
      '2. Negative Marking Impact: Every 4 wrong answers wipes out 1 whole correct mark. Strict question elimination',
      '   discipline is required in high-variance subjects like Quants and Programming.',
      '3. Target 145+ Marks: Aiming for 65+ in Part A and 80+ in Part B ensures selection well above previous year cutoffs.'
    ];
    let takeawayY = 198;
    takeawayText.forEach(line => {
      doc.text(line, margin + 4, takeawayY);
      takeawayY += 4.5;
    });


    // ==========================================
    // PAGE 2: Granular Subject Strength & Weakness Matrix
    // ==========================================
    doc.addPage();
    if (onProgress) onProgress('Rendering Page 2: Subject Strength Matrix...');
    drawPageHeader(2, 'PAGE 2: GRANULAR SUBJECT STRENGTH & WEAKNESS MATRIX');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(71, 85, 105);
    doc.text('Classification of all 13 DSSSB curriculum modules into Strong (≥70%), Moderate (48-69%), and Critical Weak (<48%).', margin, 34);

    let subjY = 40;

    // Draw all subjects table
    const renderSubjectCategory = (title: string, subjects: any[], color: [number, number, number]) => {
      doc.setFillColor(...color);
      doc.roundedRect(margin, subjY, contentWidth, 6.5, 1.5, 1.5, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(255, 255, 255);
      doc.text(title, margin + 4, subjY + 4.5);
      subjY += 9;

      subjects.forEach((subj) => {
        doc.setFillColor(248, 250, 252);
        doc.roundedRect(margin, subjY, contentWidth, 14, 1.5, 1.5, 'F');
        doc.setDrawColor(226, 232, 240);
        doc.roundedRect(margin, subjY, contentWidth, 14, 1.5, 1.5, 'D');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8.5);
        doc.setTextColor(15, 23, 42);
        doc.text(subj.subjectName, margin + 4, subjY + 5);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(100, 116, 139);
        doc.text(`[${subj.category}] • Accuracy: ${subj.accuracy}% • Correct: ${subj.correctCount} / Wrong: ${subj.incorrectCount}`, margin + 4, subjY + 9.5);

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(7.5);
        doc.setTextColor(color[0], color[1], color[2]);
        doc.text(`Focus: ${subj.highYieldTopics.slice(0, 3).join(', ')}`, margin + 4, subjY + 13);

        // Status Badge on right
        doc.setFillColor(...color);
        doc.roundedRect(pageWidth - margin - 28, subjY + 3, 24, 6, 1, 1, 'F');
        doc.setFontSize(7);
        doc.setTextColor(255, 255, 255);
        doc.text(subj.status.toUpperCase(), pageWidth - margin - 24, subjY + 7);

        subjY += 16;
      });
      subjY += 3;
    };

    if (data.weakSubjects.length > 0) {
      renderSubjectCategory(`🔴 CRITICAL WEAK MODULES (Action Required Immediately - ${data.weakSubjects.length} Areas)`, data.weakSubjects, [220, 38, 38]);
    }
    if (data.moderateSubjects.length > 0) {
      renderSubjectCategory(`🟡 MODERATE STABILITY MODULES (Target 75%+ Accuracy - ${data.moderateSubjects.length} Areas)`, data.moderateSubjects, [217, 119, 6]);
    }
    if (data.strongSubjects.length > 0) {
      renderSubjectCategory(`🟢 STRONG MASTERY MODULES (Maintain Speed & Precision - ${data.strongSubjects.length} Areas)`, data.strongSubjects, [22, 163, 74]);
    }


    // ==========================================
    // PAGE 3: 30-Day Master Strategic Study Plan
    // ==========================================
    doc.addPage();
    if (onProgress) onProgress('Rendering Page 3: 30-Day Strategic Plan...');
    drawPageHeader(3, 'PAGE 3: TAILORED 30-DAY MASTER STRATEGIC STUDY PLAN');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(71, 85, 105);
    doc.text(`Customized daily preparation protocol calibrated to eliminate ${data.weakSubjects.length} identified weak subject bottlenecks.`, margin, 34);

    let planY = 40;

    // Phases
    const phases = [
      {
        phase: 'PHASE 1: DAYS 1 - 10',
        title: data.personalizedPlan.phase1.title,
        color: [79, 70, 229] as [number, number, number],
        tasks: data.personalizedPlan.phase1.tasks,
      },
      {
        phase: 'PHASE 2: DAYS 11 - 20',
        title: data.personalizedPlan.phase2.title,
        color: [30, 58, 138] as [number, number, number],
        tasks: data.personalizedPlan.phase2.tasks,
      },
      {
        phase: 'PHASE 3: DAYS 21 - 30',
        title: data.personalizedPlan.phase3.title,
        color: [16, 185, 129] as [number, number, number],
        tasks: data.personalizedPlan.phase3.tasks,
      },
    ];

    phases.forEach((ph) => {
      doc.setFillColor(...ph.color);
      doc.roundedRect(margin, planY, contentWidth, 6.5, 1.5, 1.5, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(255, 255, 255);
      doc.text(`${ph.phase} • ${ph.title}`, margin + 4, planY + 4.5);
      planY += 8.5;

      doc.setFillColor(248, 250, 252);
      doc.roundedRect(margin, planY, contentWidth, 24, 1.5, 1.5, 'F');
      doc.setDrawColor(226, 232, 240);
      doc.roundedRect(margin, planY, contentWidth, 24, 1.5, 1.5, 'D');

      let taskY = planY + 5;
      ph.tasks.forEach((t) => {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(51, 65, 85);
        doc.text(`•  ${t}`, margin + 4, taskY);
        taskY += 4.5;
      });

      planY += 28;
    });

    // Daily Recommended Schedule (6-Hour Timetable)
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text('RECOMMENDED 6-HOUR DAILY TIMETABLE (FOR WORKING / FULL-TIME ASPIRANTS)', margin, planY + 4);
    planY += 9;

    data.personalizedPlan.dailySchedule.forEach((slot, i) => {
      if (i % 2 === 0) {
        doc.setFillColor(241, 245, 249);
        doc.rect(margin, planY, contentWidth, 6.5, 'F');
      }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(79, 70, 229);
      doc.text(slot.time, margin + 3, planY + 4.5);

      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text(slot.slot, margin + 35, planY + 4.5);

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(71, 85, 105);
      doc.text(`${slot.activity} (${slot.subject})`, margin + 75, planY + 4.5);

      planY += 7;
    });


    // ==========================================
    // PAGE 4: High-Yield Topic Matrix & Examiner Hacks
    // ==========================================
    doc.addPage();
    if (onProgress) onProgress('Rendering Page 4: High-Yield Topic Checklist...');
    drawPageHeader(4, 'PAGE 4: HIGH-YIELD TOPIC CHECKLIST & EXAMINER HACKS');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9.5);
    doc.setTextColor(30, 58, 138);
    doc.text('COMPUTER SCIENCE CORE HIGH-YIELD TOPICS WEIGHTAGE', margin, 35);

    let checkY = 40;
    data.highYieldCsChecklist.forEach((item, idx) => {
      if (idx % 2 === 0) {
        doc.setFillColor(248, 250, 252);
        doc.rect(margin, checkY, contentWidth, 8, 'F');
      }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      doc.text(item.module, margin + 4, checkY + 5.5);

      doc.setFont('helvetica', 'bold');
      doc.setTextColor(79, 70, 229);
      doc.text(`[${item.weightage}]`, margin + 60, checkY + 5.5);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(71, 85, 105);
      doc.text(item.keyFocus, margin + 85, checkY + 5.5);

      checkY += 8.5;
    });

    // Part A Formula Hacks
    checkY += 6;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9.5);
    doc.setTextColor(30, 58, 138);
    doc.text('PART A (GENERAL ABILITY) SECTIONAL SPEED HACKS', margin, checkY);
    checkY += 6;

    data.partAFormulaHacks.forEach((hackItem, idx) => {
      if (idx % 2 === 0) {
        doc.setFillColor(248, 250, 252);
        doc.rect(margin, checkY, contentWidth, 8, 'F');
      }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      doc.text(hackItem.section, margin + 4, checkY + 5.5);

      doc.setFont('helvetica', 'bold');
      doc.setTextColor(217, 119, 6);
      doc.text(`[${hackItem.weightage}]`, margin + 55, checkY + 5.5);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(71, 85, 105);
      doc.text(hackItem.hack, margin + 78, checkY + 5.5);

      checkY += 8.5;
    });

    // Official Verification Footer Box
    checkY += 8;
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(margin, checkY, contentWidth, 24, 2, 2, 'F');
    doc.setDrawColor(203, 213, 225);
    doc.roundedRect(margin, checkY, contentWidth, 24, 2, 2, 'D');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(15, 23, 42);
    doc.text('OFFICIAL VERIFICATION & PRACTICE PORTAL', margin + 5, checkY + 6);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(71, 85, 105);
    doc.text('This diagnostic dossier is electronically generated from authenticated candidate mock sessions on DSSSB PYQ Online.', margin + 5, checkY + 11);
    doc.text('For latest previous year question papers, official syllabus updates, and live mock tests, visit https://dsssbpyq.online', margin + 5, checkY + 16);
    doc.text(`Candidate Reference ID: ${data.profileId}  |  Verification Hash: SHA256-${Math.random().toString(36).substring(2, 12).toUpperCase()}`, margin + 5, checkY + 21);

    if (onProgress) onProgress('Finalizing and downloading PDF...');
    const safeName = (data.candidateName || 'Candidate').replace(/[^a-zA-Z0-9_-]/g, '_');
    doc.save(`DSSSB_TGT_CS_Diagnostic_Report_${safeName}.pdf`);

    return true;
  } catch (error) {
    console.error('Error generating PDF dossier:', error);
    throw error;
  }
}
